name: Tests on Ubuntu

on:
  push:
    branches: [ main, master, dev, develop ]
  pull_request:
    branches: [ main, master, dev, develop ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: Build googletest
      run: |
        make ./googletest-master/build/lib/libgtest.a
    - name: Build CPMEX
      run: |
        make FORCE_CPMEX
    - name: Build the others
      run: |
        make
    - name: Run tests
      run: |
        ./exe
